[package]
name = "rcheer"
version = "0.1.0"
authors = ["curtisxk38 <ck2ha@virginia.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
